import { mkdir, writeFile } from 'fs/promises'
import { dirname, extname, relative, sep } from 'path'
import { ROUTE_FILE_EXTENSIONS } from './constants'
import { transformPathToUrl } from './format'
import { getFilesRecursively } from './glob'

export interface GenerateRouteManifestOptions {
  /** Directory scanned for route files (e.g. `src/routes`). */
  routesDir: string
  /** Path of the manifest file to write (e.g. `src/routes.gen.ts`). */
  outFile: string
}

/**
 * Scans `routesDir` once and writes a manifest file at `outFile` containing a
 * static `import` per route file plus a default-exported `AnyRouter[]`. Meant
 * to run at build time (the `asterflow generate` CLI command, or a bundler
 * plugin) - the resulting imports are literal specifiers a bundler can
 * follow, unlike `loadRoutesFromDir`'s fully-dynamic `import(file)`, which
 * bundlers can't statically resolve at all. Use this for bundled/production
 * builds; `loadRoutesFromDir` (passed to `fsRoutingPlugin` as `routesDir`)
 * covers unbundled dev runs where no codegen step is wanted.
 */
export async function generateRouteManifest({ routesDir, outFile }: GenerateRouteManifestOptions): Promise<void> {
  const allFiles = await getFilesRecursively(routesDir)
  const routeFiles = allFiles
    .filter((file) => ROUTE_FILE_EXTENSIONS.has(extname(file)) && !file.endsWith('.d.ts'))
    .sort()

  const outDir = dirname(outFile)

  const imports: string[] = []
  const assignments: string[] = []
  const aliases: string[] = []

  routeFiles.forEach((file, index) => {
    const alias = `Route${index}`
    const specifier = toImportSpecifier(relative(outDir, file))
    const url = transformPathToUrl(file, routesDir)

    imports.push(`import ${alias} from '${specifier}'`)
    assignments.push(`if (!${alias}.path) ${alias}.path = ${JSON.stringify(url)}`)
    aliases.push(alias)
  })

  const body = [
    '// AUTO-GENERATED by `asterflow generate` - do not edit directly.',
    `// Source directory: ${toImportSpecifier(relative(outDir, routesDir))}`,
    ...imports,
    '',
    ...assignments,
    '',
    `export default [${aliases.join(', ')}]`,
    ''
  ].join('\n')

  await mkdir(outDir, { recursive: true })
  await writeFile(outFile, body)
}

function toImportSpecifier(relativePath: string): string {
  const withoutExt = relativePath.replace(/\.(ts|tsx|js|jsx)$/, '')
  const posix = withoutExt.split(sep).join('/')
  return posix.startsWith('.') ? posix : `./${posix}`
}
