/**
 * Regenerates plugins/multipart/src/types/mime.ts from IANA's official
 * per-category media-type registries.
 *
 * Usage: bun run scripts/generate-mime-types.ts
 */
import { writeFile } from 'fs/promises'
import { join } from 'path'

const CLI = '\x1b[34mCLI\x1b[0m'

const CATEGORIES = [
  { key: 'application', typeName: 'ApplicationMimeType' },
  { key: 'audio', typeName: 'AudioMimeType' },
  { key: 'font', typeName: 'FontMimeType' },
  { key: 'image', typeName: 'ImageMimeType' },
  { key: 'message', typeName: 'MessageMimeType' },
  { key: 'model', typeName: 'ModelMimeType' },
  { key: 'text', typeName: 'TextMimeType' },
  { key: 'video', typeName: 'VideoMimeType' }
] as const

const OUTPUT_PATH = join(import.meta.dirname, '../plugins/multipart/src/types/mime.ts')

/**
 * Parses a single IANA media-types CSV row into its `Template` column
 * (the full `category/name` MIME string), skipping the header row and any
 * row too short to contain one (IANA leaves the Template column blank for
 * a small number of provisional/unregistered entries).
 */
function parseTemplates(csv: string): string[] {
  const lines = csv.split('\n').slice(1)
  const templates: string[] = []

  for (const line of lines) {
    if (line.trim().length <= 3) continue

    const fields = line.split(',')
    const template = fields[1]?.trim()
    if (!template || !template.includes('/')) continue

    templates.push(template)
  }

  return templates
}

async function fetchCategory(category: string): Promise<string[]> {
  const response = await fetch(`https://www.iana.org/assignments/media-types/${category}.csv`)
  if (!response.ok) throw new Error(`Failed to fetch ${category}.csv: ${response.status} ${response.statusText}`)

  return parseTemplates(await response.text())
}

async function main() {
  console.log(`${CLI} Fetching MIME type registries from IANA...`)

  const results = await Promise.all(CATEGORIES.map(async ({ key, typeName }) => {
    const templates = [...new Set(await fetchCategory(key))].sort()
    console.log(`${CLI} ${key}: ${templates.length} entries`)
    return { typeName, templates }
  }))

  const lines: string[] = []
  lines.push('/**')
  lines.push(' * Generated by scripts/generate-mime-types.ts from IANA\'s official')
  lines.push(' * per-category media-type registries (https://www.iana.org/assignments/media-types).')
  lines.push(' * Do not edit by hand - re-run the script to refresh this file.')
  lines.push(' */')
  lines.push('')

  for (const { typeName, templates } of results) {
    lines.push(`export type ${typeName} =`)
    for (const template of templates) {
      lines.push(`  | '${template}'`)
    }
    lines.push('')
  }

  lines.push(`export type KnownMimeType = ${results.map((r) => r.typeName).join(' | ')}`)
  lines.push('')
  lines.push('/**')
  lines.push(' * All IANA-registered MIME types, plus an escape hatch (`string & {}`) so')
  lines.push(' * custom or vendor-specific MIME types not in the registry still type-check.')
  lines.push(' * The intersection with `{}` keeps literal-string autocomplete for the known')
  lines.push(' * cases working in editors that support it.')
  lines.push(' */')
  lines.push('export type MimeType = KnownMimeType | (string & {})')
  lines.push('')

  await writeFile(OUTPUT_PATH, lines.join('\n'))

  const total = results.reduce((sum, r) => sum + r.templates.length, 0)
  console.log(`${CLI} Wrote ${total} MIME types to ${OUTPUT_PATH}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
